(()=>{
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const liveUrl=()=>String(window.JOTRIP_LIVE_API_URL||'').replace(/\/$/,'');
function airline(r){return r?.airline_name||r?.airline||r?.airline_code||'Chưa rõ hãng'}
function toMin(v){const m=String(v||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function actualDelay(r){const direct=Number(r?.actual_delay_minutes);if(Number.isFinite(direct))return direct;if(!r?.actual_time)return null;const s=toMin(r?.scheduled_time),a=toMin(r?.actual_time);if(s==null||a==null)return null;let d=a-s;if(d>720)d-=1440;if(d<-720)d+=1440;return d}
function stationName(s){return String(s||'').replace('HO CHI MINH','TP.HCM').replace('HA NOI','HÀ NỘI').replace('DA NANG','ĐÀ NẴNG').replace('HAI PHONG','HẢI PHÒNG').replace('CAN THO','CẦN THƠ').replace('PUDONG- SHANGHAI','SHANGHAI').replace('XIANYANG-XI AN',"XI'AN")}
function score(records,direction){const m=new Map();for(const r of records||[]){if(r?.direction!==direction)continue;const name=airline(r),k=name.toUpperCase();if(!m.has(k))m.set(k,{name,scheduled:0,total:0,on:0,late:0,delaySum:0});const a=m.get(k);a.scheduled++;const d=actualDelay(r);if(!r?.actual_time||!Number.isFinite(d)||/CANCELLED/.test(r?.status_code||''))continue;a.total++;if(d<=15)a.on++;else{a.late++;a.delaySum+=Math.max(0,d)}}return[...m.values()].sort((a,b)=>b.scheduled-a.scheduled||b.total-a.total||b.on-a.on||a.name.localeCompare(b.name,'vi'))}
function ensureLayout(){const host=$('.airline-performance');if(!host||host.dataset.splitOtp==='1')return;host.dataset.splitOtp='1';host.innerHTML=`
  <div class="card-head"><div><span class="section-kicker">AIRLINE PERFORMANCE</span><h3>Đúng giờ / trễ theo hãng</h3></div><div class="muted">Tất cả hãng trong ngày</div></div>
  <p class="airline-note"><b>OTP15</b> = On-Time Performance theo ngưỡng 15 phút. Một chuyến được tính đúng giờ khi <b>giờ thực tế</b> không muộn quá 15 phút so với giờ lịch. Chỉ chấm những chuyến đã có giờ thực tế; chuyến hủy không được chấm. “Trễ TB” là mức trễ trung bình của các chuyến trễ trên 15 phút.</p>
  <div class="otp-direction-grid">
    <section class="otp-direction-card"><div class="otp-direction-head"><div><span class="section-kicker">ARRIVALS</span><h4>Đến Phú Quốc</h4></div><div class="otp-summary"><b id="arrivalOtpRate">-</b><span>ON TIME ≤15'</span><small id="arrivalOtpSample">- chuyến</small></div></div><div class="airline-table-wrap"><table class="airline-table"><thead><tr><th>Hãng</th><th>Tổng chuyến</th><th>Có giờ thực tế</th><th>Đúng giờ</th><th>Trễ &gt;15'</th><th>OTP15</th><th>Trễ TB</th></tr></thead><tbody id="airlineArrivalBody"></tbody></table></div></section>
    <section class="otp-direction-card"><div class="otp-direction-head"><div><span class="section-kicker">DEPARTURES</span><h4>Rời Phú Quốc</h4></div><div class="otp-summary"><b id="departureOtpRate">-</b><span>ON TIME ≤15'</span><small id="departureOtpSample">- chuyến</small></div></div><div class="airline-table-wrap"><table class="airline-table"><thead><tr><th>Hãng</th><th>Tổng chuyến</th><th>Có giờ thực tế</th><th>Đúng giờ</th><th>Trễ &gt;15'</th><th>OTP15</th><th>Trễ TB</th></tr></thead><tbody id="airlineDepartureBody"></tbody></table></div></section>
  </div>`;
const style=document.createElement('style');style.textContent=`.otp-direction-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.otp-direction-card{min-width:0;border:1px solid #e7eef3;border-radius:16px;padding:13px;background:#fbfdfe}.otp-direction-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.otp-direction-head h4{margin:3px 0 0;font-size:15px}.otp-summary{text-align:right;display:grid;line-height:1.05}.otp-summary b{font-size:22px}.otp-summary span{font-size:9px;font-weight:850;letter-spacing:.05em;color:#708095}.otp-summary small{margin-top:4px;color:#708095;font-size:9.5px}@media(max-width:980px){.otp-direction-grid{grid-template-columns:1fr}}`;document.head.appendChild(style)}
function renderTable(rows,bodyId,rateId,sampleId){const body=$('#'+bodyId);if(!body)return;body.innerHTML=rows.length?rows.map(a=>{const onPct=a.total?a.on*100/a.total:null,avg=a.late?a.delaySum/a.late:0;return `<tr><td><strong>${esc(a.name)}</strong></td><td>${a.scheduled}</td><td>${a.total}</td><td>${a.on}</td><td>${a.late}</td><td class="rate-good">${onPct==null?'-':onPct.toFixed(1)+'%'}</td><td>${a.late?Math.round(avg)+' phút':'-'}</td></tr>`}).join(''):'<tr><td colspan="7">Chưa có chuyến trong ngày.</td></tr>';const total=rows.reduce((n,a)=>n+a.total,0),on=rows.reduce((n,a)=>n+a.on,0);const rate=$('#'+rateId),sample=$('#'+sampleId);if(rate)rate.textContent=total?(on*100/total).toFixed(1)+'%':'-';if(sample)sample.textContent=total?`${on}/${total} chuyến đúng giờ`:'Chưa đủ dữ liệu OTP'}
function renderAllStations(latest){const s=latest?.summary||{},merged={};for(const [k,v] of Object.entries(s.arrivals_by_station||{}))merged[k]=(merged[k]||0)+v;for(const [k,v] of Object.entries(s.departures_by_station||{}))merged[k]=(merged[k]||0)+v;const routes=Object.entries(merged).sort((a,b)=>b[1]-a[1]||stationName(a[0]).localeCompare(stationName(b[0]),'vi'));const max=routes[0]?.[1]||1;const bars=$('#routeBars');if(bars)bars.innerHTML=routes.map(([k,v])=>`<div class="route-bar"><span>${esc(stationName(k))}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('');const title=bars?.closest('.analytics-block')?.querySelector('h4');if(title)title.textContent='Tất cả điểm đi / đến'}
function render(records,latest){ensureLayout();renderTable(score(records,'arrival'),'airlineArrivalBody','arrivalOtpRate','arrivalOtpSample');renderTable(score(records,'departure'),'airlineDepartureBody','departureOtpRate','departureOtpSample');renderAllStations(latest)}
if(typeof renderAnalytics==='function'){const baseRenderAnalytics=renderAnalytics;renderAnalytics=function(){baseRenderAnalytics();try{renderAllStations(typeof state!=='undefined'?state.latest:null)}catch(_){}}}
async function load(){try{const base=liveUrl();if(!base)return;const u=new URL(base);if(window.JOTRIP_BOARD_DATE)u.searchParams.set('date',window.JOTRIP_BOARD_DATE);u.searchParams.set('t',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const p=await r.json();render(p?.latest?.records||[],p?.latest)}catch(e){console.warn('Không tải được thống kê hãng bay',e)}}
window.addEventListener('jotrip:board-date',load);load();setInterval(load,60000);
const statusScript=document.createElement('script');statusScript.src='./status-summary.js?v=20260916a';document.head.appendChild(statusScript);
})();
