const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-sunairport/data/sunairport';
const $=s=>document.querySelector(s);
const state={days:[],direction:'all',time:'all',airline:'all',query:''};
function ht(key,fallback,vars){try{return typeof window.JT_HISTORY_T==='function'?window.JT_HISTORY_T(key,vars):fallback}catch(_){return fallback}}
function vnDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}-${o.month}-${o.day}`}
function fold(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toUpperCase().replace(/\s+/g,' ').trim()}
function hhmm(v){const m=String(v??'').match(/^(\d{2})(\d{2})/);return m?`${m[1]}:${m[2]}`:String(v||'').match(/^\d{1,2}:\d{2}$/)?.[0]||null}
function mins(v){const t=hhmm(v);if(!t)return null;const [h,m]=t.split(':').map(Number);return h*60+m}
function diff(a,b){const x=mins(a),y=mins(b);if(x==null||y==null)return null;let d=y-x;if(d<0)d+=1440;return d>=0&&d<=720?d:null}
function signedDiff(a,b){const x=mins(a),y=mins(b);if(x==null||y==null)return null;let d=y-x;if(d>720)d-=1440;if(d<-720)d+=1440;return d}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function sourceStatus(r){return String(r.notesVn||r.notesEn||r.status||r.remarks||'').trim()}
function airline(r){return r.airlineName||r.airline||r.airlineCode||ht('unknownAirline','Chưa rõ hãng')}
function checkinTime(text){const m=String(text||'').match(/LÀM THỦ TỤC LÚC\s*(\d{1,2}:\d{2})/i);return m?m[1]:null}
function delayed(r){const u=fold(sourceStatus(r));if(/TRE|DELAY|DOI GIO|RESCHEDULED|POSTPONED|HOAN/.test(u))return true;const s=hhmm(r.scheduledTime),e=hhmm(r.estimatedTime);return !!(s&&e&&s!==e&&diff(s,e)>0)}
function cancelled(r){return /HUY|CANCEL/.test(fold(sourceStatus(r)))}
function delayMin(r){return delayed(r)?diff(hhmm(r.scheduledTime),hhmm(r.estimatedTime)):0}
function actualDelay(r){return hhmm(r.actualTime)?signedDiff(hhmm(r.scheduledTime),hhmm(r.actualTime)):null}
function humanStatus(r){const raw=sourceStatus(r),u=fold(raw),ci=checkinTime(raw);if(ci)return `Check-in từ ${ci}`;if(u.includes('DANG LAM THU TUC'))return 'Đang check-in';if(u.includes('QUAY THU TUC DA DONG'))return 'Check-in đã đóng';if(u.includes('CUA KHOI HANH DA DONG'))return 'Cửa khởi hành đã đóng';if(u.includes('HANH KHACH DANG LEN TAU BAY')||u.includes('BOARDING'))return 'Đang lên máy bay';if(u.includes('DA HA CANH')||u.includes('ARRIVED'))return 'Đã hạ cánh';if(u.includes('DA CAT CANH')||u.includes('DEPARTED'))return 'Đã cất cánh';if(cancelled(r))return 'Đã hủy';if(delayed(r)){const d=delayMin(r);return d>0?`Trễ ${d} phút`:'Trễ / đổi giờ'}return raw||'Đúng giờ / chưa ghi nhận trễ'}
function statusClass(r){if(cancelled(r))return'red';if(delayed(r))return'amber';const u=fold(sourceStatus(r));if(/DA HA CANH|DA CAT CANH|ARRIVED|DEPARTED/.test(u))return'green';if(/LAM THU TUC|BOARDING|LEN TAU BAY/.test(u))return'blue';return''}
function withinBank(r,bank){if(bank==='all')return true;const h=Number((hhmm(r.scheduledTime)||'99:00').slice(0,2));const [a,b]=bank.split('-').map(Number);return h>=a&&h<b}
function dateList(a,b){const out=[];let d=new Date(a+'T00:00:00Z'),end=new Date(b+'T00:00:00Z');while(d<=end&&out.length<31){out.push(d.toISOString().slice(0,10));d=new Date(d.getTime()+86400000)}return out}
async function fetchJson(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function fetchEvents(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(r.status===404)return[];if(!r.ok)return[];const text=await r.text();return text.split('\n').filter(Boolean).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean)}
function key(direction,row){return row?.id!=null?`${direction}|id:${row.id}`:`${direction}|${fold(row?.flightNo)}|${row?.scheduledTime||''}|${fold(row?.cityName)}`}
function fmtEvent(e){if(e.type==='FIRST_SEEN')return ht('eventFirstSeenDetail','Ghi nhận chuyến lần đầu trong JoTrip AutoSync.');const names={estimatedTime:ht('fieldEstimated','Giờ dự kiến'),actualTime:ht('fieldActual','Giờ thực tế'),notesVn:ht('fieldStatus','Trạng thái'),gate:ht('fieldGate','Cửa'),belt:ht('fieldBelt','Băng chuyền'),parkingBay:ht('fieldParking','Vị trí đỗ'),scheduledTime:ht('fieldScheduled','Giờ lịch'),boardingStart:ht('fieldBoardingStart','Bắt đầu boarding'),boardingFinish:ht('fieldBoardingFinish','Kết thúc boarding')};return Object.entries(e.changes||{}).map(([f,x])=>{let from=x.from??'∅',to=x.to??'∅';if(f==='notesVn'&&typeof window.JT_HISTORY_STATUS==='function'){from=window.JT_HISTORY_STATUS(from);to=window.JT_HISTORY_STATUS(to)}return `${names[f]||f}: ${from} → ${to}`}).join(' · ')||ht('eventChangedFallback','Dữ liệu chuyến có thay đổi.')}
function eventTime(e){try{const loc=typeof window.JT_HISTORY_LANG==='function'?window.JT_HISTORY_LANG():'vi';const locale=loc==='vi'?'vi-VN':loc==='ko'?'ko-KR':loc==='ru'?'ru-RU':loc==='zh'?'zh-CN':'en-US';return new Date(e.at).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}catch{return'--:--'}}
async function load(){let from=$('#historyFrom').value||vnDate(),to=$('#historyTo').value||from;if(to<from)[from,to]=[to,from];$('#historyFrom').value=from;$('#historyTo').value=to;const dates=dateList(from,to);$('#archiveHealth').className='archive-pill';$('#archiveHealth').textContent=ht('loading','ĐANG TẢI');$('#historyError').classList.add('hidden');try{const days=await Promise.all(dates.map(async date=>{try{const [raw,events]=await Promise.all([fetchJson(`${DATA_BASE}/raw/${date}.json`),fetchEvents(`${DATA_BASE}/history/${date}/events.jsonl`)]);return{date,raw,events}}catch{return null}}));state.days=days.filter(Boolean);if(!state.days.length)throw new Error('no data');$('#archiveHealth').className='archive-pill good';$('#archiveHealth').textContent=`${state.days.length} ${state.days.length===1?ht('day','NGÀY'):ht('days','NGÀY')} · ${allRows().length} ${ht('flightWord','CHUYẾN')}`;refreshAirlines();render()}catch(e){state.days=[];$('#archiveHealth').className='archive-pill bad';$('#archiveHealth').textContent=ht('noData','CHƯA CÓ DỮ LIỆU');$('#historyError').textContent=ht('noDataRange','Chưa có dữ liệu lưu trong khoảng {from} - {to}.',{from,to});$('#historyError').classList.remove('hidden');render()}}
function allRows(){const rows=[];for(const d of state.days){for(const r of d.raw?.arrivals||[])rows.push({...r,_direction:'arrival',_date:d.date,_events:d.events||[]});for(const r of d.raw?.departures||[])rows.push({...r,_direction:'departure',_date:d.date,_events:d.events||[]})}return rows}
function filteredRows(){let rows=allRows();if(state.direction!=='all')rows=rows.filter(r=>r._direction===state.direction);if(state.airline!=='all')rows=rows.filter(r=>fold(airline(r))===state.airline);rows=rows.filter(r=>withinBank(r,state.time));if(state.query){const q=fold(state.query);rows=rows.filter(r=>fold([r.flightNo,airline(r),r.cityName,r.route,r.country,sourceStatus(r)].join(' ')).includes(q))}rows.sort((a,b)=>a._date.localeCompare(b._date)||(mins(a.scheduledTime)??9999)-(mins(b.scheduledTime)??9999));return rows}
function refreshAirlines(){const sel=$('#historyAirline'),current=state.airline;const names=[...new Set(allRows().map(airline).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));sel.innerHTML='<option value="all">'+esc(ht('allAirlines','Tất cả hãng'))+'</option>'+names.map(n=>`<option value="${esc(fold(n))}">${esc(n)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current;else state.airline='all'}
function airlineStats(rows,direction){const m=new Map();for(const r of rows){if(r._direction!==direction)continue;const d=actualDelay(r);if(d==null||cancelled(r))continue;const n=airline(r),k=fold(n);if(!m.has(k))m.set(k,{name:n,total:0,on:0,late:0,sum:0});const a=m.get(k);a.total++;if(d<=15)a.on++;else{a.late++;a.sum+=Math.max(0,d)}}return [...m.values()].sort((a,b)=>b.total-a.total||b.on-a.on)}
function renderAirlineTable(rows,direction,bodyId,rateId,sampleId){const stats=airlineStats(rows,direction),body=$('#'+bodyId);body.innerHTML=stats.length?stats.map(a=>{const op=a.total?a.on*100/a.total:0,lp=a.total?a.late*100/a.total:0,av=a.late?a.sum/a.late:0;return `<tr><td><strong>${esc(a.name)}</strong></td><td>${a.total}</td><td>${a.on}</td><td>${a.late}</td><td class="rate-good">${op.toFixed(1)}%</td><td class="rate-watch">${lp.toFixed(1)}%</td><td>${a.late?Math.round(av)+' '+esc(ht('minuteUnit','phút')):'-'}</td></tr>`}).join(''):`<tr><td colspan="7">${esc(ht('notEnoughActual','Chưa đủ chuyến có giờ thực tế để tính tỷ lệ đúng giờ.'))}</td></tr>`;const total=stats.reduce((n,a)=>n+a.total,0),on=stats.reduce((n,a)=>n+a.on,0);$('#'+rateId).textContent=total?(on*100/total).toFixed(1)+'%':'-';$('#'+sampleId).textContent=total?ht('onTimeSample','{on}/{total} chuyến đúng giờ',{on,total}):ht('noSample','0 chuyến')}
function renderMetrics(rows){const scored=rows.map(r=>({r,d:actualDelay(r)})).filter(x=>x.d!=null&&!cancelled(x.r)),on=scored.filter(x=>x.d<=15),late=scored.filter(x=>x.d>15),lateMinutes=late.map(x=>Math.max(0,x.d));$('#hTotal').textContent=rows.length;$('#hArrivals').textContent=rows.filter(r=>r._direction==='arrival').length;$('#hDepartures').textContent=rows.filter(r=>r._direction==='departure').length;$('#hOnTime').textContent=on.length;$('#hDelayed').textContent=late.length;$('#hOnTimeRate').textContent=scored.length?(on.length*100/scored.length).toFixed(1)+'%':'-';$('#hAvgDelay').textContent=lateMinutes.length?Math.round(lateMinutes.reduce((a,b)=>a+b,0)/lateMinutes.length)+' '+ht('minuteUnit','phút'):'-';$('#historyCount').textContent=ht('suitable','{n} chuyến phù hợp',{n:rows.length})+' · '+ht('actualCount','{n} chuyến có giờ thực tế',{n:scored.length});const f=$('#historyFrom').value,t=$('#historyTo').value;const fd=f.split('-').reverse().join('/'),td=t.split('-').reverse().join('/');$('#historyTitle').textContent=f===t?ht('dataDate','Dữ liệu {date}',{date:fd}):ht('dataRange','Dữ liệu {from} - {to}',{from:fd,to:td})}
function ensureStyle(){if(document.getElementById('historyOtpStyle'))return;const style=document.createElement('style');style.id='historyOtpStyle';style.textContent=`.otp-direction-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.otp-direction-card{min-width:0;border:1px solid #e7eef3;border-radius:16px;padding:13px;background:#fbfdfe}.otp-direction-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.otp-direction-head h4{margin:3px 0 0;font-size:15px}.otp-summary{text-align:right;display:grid;line-height:1.05}.otp-summary b{font-size:22px}.otp-summary span{font-size:9px;font-weight:850;letter-spacing:.05em;color:#708095}.otp-summary small{margin-top:4px;color:#708095;font-size:9.5px}@media(max-width:980px){.otp-direction-grid{grid-template-columns:1fr}}`;document.head.appendChild(style)}
function render(){ensureStyle();const rows=filteredRows();renderMetrics(rows);if(!rows.length){$('#historyList').innerHTML=`<div class="history-empty">${esc(ht('noMatch','Không có chuyến phù hợp với bộ lọc hiện tại.'))}</div>`;return}$('#historyList').innerHTML=rows.map(r=>{const events=(r._events||[]).filter(e=>e.key===key(r._direction,r)),scheduled=hhmm(r.scheduledTime)||'--:--',estimated=hhmm(r.estimatedTime),actual=hhmm(r.actualTime),status=humanStatus(r),route=r.route||r.cityName||'',changed=events.filter(e=>e.type==='CHANGED').length,sub=[airline(r),r._date,changed?ht('changes','{n} lần thay đổi',{n:changed}):null].filter(Boolean).join(' · '),timeSub=actual?ht('actual','Thực tế {time}',{time:actual}):estimated&&estimated!==scheduled?ht('estimated','Dự kiến {time}',{time:estimated}):(r._direction==='arrival'?ht('toPqc','Đến PQC'):ht('fromPqc','Rời PQC')),timeline=events.length?events.map(e=>`<div class="event-line"><span class="event-time">${esc(eventTime(e))}</span><span class="event-type">${esc(e.type==='FIRST_SEEN'?ht('firstSeen','GHI NHẬN'):ht('changed','THAY ĐỔI'))}</span><span class="event-detail">${esc(fmtEvent(e))}</span></div>`).join(''):`<div class="event-line"><span></span><span></span><span class="event-detail">${esc(ht('noEvent','Chưa ghi nhận thay đổi trong lịch sử sự kiện.'))}</span></div>`;return `<div class="history-row"><div class="history-row-main"><div class="h-flight">${esc(r.flightNo||'')}</div><div class="h-time">${esc(scheduled)}<small>${esc(timeSub)}</small></div><div class="h-route">${esc(route)}<small>${esc(sub)}</small></div><div class="h-type">${esc(r._direction==='arrival'?ht('arrType','CHUYẾN ĐẾN'):ht('depType','CHUYẾN ĐI'))}</div><div class="h-status ${statusClass(r)}">${esc(typeof window.JT_HISTORY_STATUS==='function'?window.JT_HISTORY_STATUS(status):status)}</div><div class="h-chevron">›</div></div><div class="history-timeline">${timeline}</div></div>`}).join('');document.querySelectorAll('.history-row-main').forEach(el=>el.onclick=()=>el.parentElement.classList.toggle('open'))}
const today=vnDate();$('#historyFrom').value=today;$('#historyTo').value=today;
$('#historyFrom').addEventListener('change',load);$('#historyTo').addEventListener('change',load);$('#historyDirection').addEventListener('change',e=>{state.direction=e.target.value;render()});$('#historyTime').addEventListener('change',e=>{state.time=e.target.value;render()});$('#historyAirline').addEventListener('change',e=>{state.airline=e.target.value;render()});$('#historySearch').addEventListener('input',e=>{state.query=e.target.value.trim();render()});
load();
